#  20. Crie uma lista de 5 letras e converta para uma unica string com join.

'''
JOIN:

.join() em Python serve para juntar (ou concatenar) os elementos de uma lista (ou de qualquer iterável de strings) 
em uma única string, usando um separador que você escolher.

'''
# lista_de_palavras = ["Olá", "mundo", "em", "Python"]
# separador = " "  # Separador é um espaço

# frase_unida = separador.join(lista_de_palavras)

# print(frase_unida)  # Saída: Olá mundo em Python

Lista = ['V', 'I', 'A', 'D', 'O']
Juntinho = ''

frase_unida = Juntinho.join(Lista)
print(frase_unida)


